version: '3'

services:

  app:
    build:
      context: ./app
    image: evertoncrispim/app
    container_name: app
    entrypoint: sh -c "npm install && npm run dev"
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    tty: true
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - app

  database:
    image: mysql:5.7
    container_name: database
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

volumes:
  mysql:
    driver: local

networks:
  node-network:
    driver: bridge