version: '3'

services:

  node_app:
    build:
      context: ./node_app
    image: evertoncrispim/node_app
    container_name: node_app
    networks:
      - node-network
    volumes:
      - ./node_app:/usr/src/app
      - /app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - node_app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - .mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge